- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builin.command: dnf moduel enable nodejs:20 -y

  -name: install nodejs
    ansible.buitlin.package:
      name: nodejs
      state: present