- name: Configuration of Backend
  hosts: backend
  become: yes
  vars:
    my_sql_password: ExpenseApp@1
    host_details: mysql.hemanthkumar.online
    # database_name: expense_db
  tasks:
    - name: Installing the pre-required Python packages
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9
    - name: Disabling the default Node.js version
      ansible.builtin.command:
        cmd: dnf module disable nodejs -y
    - name: Enabling Node.js version 20
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y
    - name: Installing Node.js and MySQL
      ansible.builtin.package:
        name:
          - nodejs
          - mysql
        state: present
    - name: Enabling and starting backend service
      ansible.builtin.service:
        name: backend
        state: started
        enabled: yes
    - name: Create 'expense' user
      ansible.builtin.user:
        name: expense
    - name: Create the application directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: Extract the backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    - name: install nodejs
      ansible.builtin.package:
       name: "{{ item }}"
       state: present
      loop:
       - nodejs
       - mysql
    # - name: Installing backend dependencies
    #   ansible.builtin.command:
    #     cmd: npm install
    #     args:
    #       chdir: /app
    - name: Copy backend service configuration
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Import MySQL data
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ my_sql_password }}"
        login_host: "{{ host_details }}"
        target: /app/schema/backend.sql
        name: all
        state: import
    - name: Reload and restart the backend service
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: backend