- name: configure mysql server 
  hosts: mysql
  become: yes 
  tasks:
  - name: install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.buiitin.service:
      name: musqld
      state: started 
      enabled: yes
